"""
Django settings for quickBackend project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 文件上传路径配置
MEDIA_URL = '/media/'  # 访问上传文件的 URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件存储的本地目录

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r!9kf*9zfso+m1z^3_le^x&tv_i0t1(y5@a7@6b^-dr^1pwum0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.1.100', 'localhost', '::1', '*']  # 添加你想允许的 IP 或域名
ALLOWED_HOSTS = [ 'localhost', '::1', '*']  # 添加你想允许的 IP 或域名

# Application definition

INSTALLED_APPS = [
    #核心
    "rest_framework",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 自定义应用
    'image_manager',
    "testapi",
    # 其他应用
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 其他中间件
'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]

ROOT_URLCONF = 'quickBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quickBackend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,  # 指定日志配置的版本号
    'disable_existing_loggers': False,  # 是否禁用已存在的日志记录器，False 表示保留默认的日志配置
    'formatters': {  # 定义日志格式器
        'verbose': {  # 名为 verbose 的日志格式器
            'format': '{levelname} {asctime} {module} {message}',  # 定义详细格式的日志输出模板
            'style': '{',  # 指定格式模板的样式
        },
        'simple': {  # 名为 simple 的日志格式器
            'format': '{levelname} {message}',  # 定义简单格式的日志输出模板
            'style': '{',  # 指定格式模板的样式
        },
    },
    'handlers': {  # 定义日志处理器
        'file': {  # 定义一个保存日志到文件的处理器
            'level': 'ERROR',  # 处理 ERROR 及以上级别的日志
            'class': 'logging.FileHandler',  # 使用 FileHandler 类处理日志
            'filename': 'django_error.log',  # 指定日志保存的文件路径
            'formatter': 'verbose',  # 使用 verbose 格式器格式化日志
            'encoding': 'utf-8',  # 设置日志文件的编码为 UTF-8
        },
        'console': {  # 定义一个输出日志到控制台的处理器
            'level': 'WARNING',  # 处理 ERROR 及以上级别的日志
            'class': 'logging.StreamHandler',  # 使用 StreamHandler 类处理日志
            'formatter': 'simple',  # 使用 simple 格式器格式化日志
        },
    },
    'loggers': {  # 定义日志记录器
        'django': {  # 名为 django 的日志记录器
            'handlers': ['file', 'console'],  # 使用 file 和 console 两个处理器
            'level': 'DEBUG',  # 记录 DEBUG 及以上级别的日志
            'propagate': True,  # 是否将日志向上传递到父记录器
        },
        'myapp': {  # 名为 myapp 的自定义日志记录器
            'handlers': ['file', 'console'],  # 使用 file 和 console 两个处理器
            'level': 'DEBUG',  # 记录 DEBUG 及以上级别的日志
            'propagate': False,  # 不向上传递日志
        },
    },
}
