# Generated by Django 5.1.6 on 2025-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.ImageField(default='default.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
